export const SESSION_TYPES = {
    FETCH_USER: 'FETCH_USER',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    ACKNOWLEDGE_ERROR: 'ACKNOWLEDGE_ERROR',
    INIT: 'INIT'
}

export const STYLE_TYPES = {
    GET_FONT: 'GET_FONT',
    LOADING_FONT: 'LOADING_FONT',
    FONT_LOAD_SUCCESS: 'FONT_LOAD_SUCCESS'
}

export const BOOK_TYPES = {
    SET_BOOK: 'SET_BOOK',
    LOADING_BOOK: 'LOADING_BOOK',
    ACKNOWLEDGE_ERROR: 'ACKNOWLEDGE_ERROR',
    INIT: 'INIT'
}